# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autoclose = {
    pname = "autoclose";
    version = "d8bebaaf8c48bd0cd0645d20592548eab279fea3";
    src = fetchgit {
      url = "https://github.com/m4xshen/autoclose.nvim";
      rev = "d8bebaaf8c48bd0cd0645d20592548eab279fea3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-HBlIF+7UvYX7K0lYhL7z9v24AIQTafjY51o3+HIxgkg=";
    };
    date = "2023-08-07";
  };
  bufdelete-nvim = {
    pname = "bufdelete-nvim";
    version = "07d1f8ba79dec59d42b975a4df1c732b2e4e37b4";
    src = fetchgit {
      url = "https://github.com/famiu/bufdelete.nvim";
      rev = "07d1f8ba79dec59d42b975a4df1c732b2e4e37b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UubYRfRAXZ89WOc3QFMvAMjNjLW6bV4nDgSa1CRZkIM=";
    };
    date = "2023-06-29";
  };
  bufferline-lua = {
    pname = "bufferline-lua";
    version = "417b303328118b6d836ae330142e88771c48a8a3";
    src = fetchgit {
      url = "https://github.com/akinsho/bufferline.nvim";
      rev = "417b303328118b6d836ae330142e88771c48a8a3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-jsjT56YWsFb9Qr/mjmwpOm9thYkScnSCOZ+MPzaz1DM=";
    };
    date = "2023-08-11";
  };
  comment = {
    pname = "comment";
    version = "0236521ea582747b58869cb72f70ccfa967d2e89";
    src = fetchgit {
      url = "https://github.com/numToStr/Comment.nvim";
      rev = "0236521ea582747b58869cb72f70ccfa967d2e89";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+dF1ZombrlO6nQggufSb0igXW5zwU++o0W/5ZA07cdc=";
    };
    date = "2023-08-07";
  };
  conjure = {
    pname = "conjure";
    version = "0d9b823db06cc11e6115b54297f690dff10c0299";
    src = fetchgit {
      url = "https://github.com/Olical/conjure";
      rev = "0d9b823db06cc11e6115b54297f690dff10c0299";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Rae5SihnvnalFtNZ+VInUBRLBTilFGUj797lgKVw92g=";
    };
    date = "2023-08-04";
  };
  coq = {
    pname = "coq";
    version = "af92b636ceee8c657463fd816146b28d43ace732";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq.artifacts";
      rev = "af92b636ceee8c657463fd816146b28d43ace732";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-obWiy0nmUc/UBu9ok80A955FVLIwklIjEM1AV6BPJek=";
    };
    date = "2023-08-22";
  };
  coq_3p = {
    pname = "coq_3p";
    version = "7df79a99f2b2070bc90db60242d372d0e5fc60bf";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq.thirdparty";
      rev = "7df79a99f2b2070bc90db60242d372d0e5fc60bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oR7tAYMX3dufdFN2rKYlW1O8xoshM1zo0BwnFoTtExI=";
    };
    date = "2023-08-22";
  };
  coq_nvim = {
    pname = "coq_nvim";
    version = "cb44d4df9caa4a5a1534f4919d9f595e7c9bf6bf";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq_nvim";
      rev = "cb44d4df9caa4a5a1534f4919d9f595e7c9bf6bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gEaUXSJzsApxuz96s4IosT1fnf+UcUGpAVOthQcekaY=";
    };
    date = "2023-08-22";
  };
  crates = {
    pname = "crates";
    version = "d5caf28aba49e81ac4099426231f3cf3c151013a";
    src = fetchgit {
      url = "https://github.com/saecki/crates.nvim";
      rev = "d5caf28aba49e81ac4099426231f3cf3c151013a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-09tqoU9zo32+zpP/ybo6bbDxmdzAcr3a0xU7ZKuN3pg=";
    };
    date = "2023-08-08";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "749267aaa863c30d721c9913699c5d94e0c07dd3";
    src = fetchgit {
      url = "https://github.com/lewis6991/gitsigns.nvim";
      rev = "749267aaa863c30d721c9913699c5d94e0c07dd3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xMcR+5hN3SRXNewCfSGNXwaKxaHhzGWCBjb2n19MTPs=";
    };
    date = "2023-08-19";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "9637670896b68805430e2f72cf5d16be5b97a22a";
    src = fetchgit {
      url = "https://github.com/lukas-reineke/indent-blankline.nvim";
      rev = "9637670896b68805430e2f72cf5d16be5b97a22a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1EpjFIJ5GK9NXS6dTMJ71w/AtLtR6Q5HrAXCIRNOBAY=";
    };
    date = "2023-08-22";
  };
  lazy-lsp = {
    pname = "lazy-lsp";
    version = "4b10237a7f9e5ab678eb384a4266e2e28e8472f7";
    src = fetchgit {
      url = "https://github.com/dundalek/lazy-lsp.nvim";
      rev = "4b10237a7f9e5ab678eb384a4266e2e28e8472f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-zTupCULojjlLBgYuLeL86ugMR4bNONQp3us89PbXdOU=";
    };
    date = "2023-08-11";
  };
  lspkind = {
    pname = "lspkind";
    version = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
    src = fetchgit {
      url = "https://github.com/onsails/lspkind.nvim";
      rev = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-S+qZm51hw/cRujIfHV/1x1fYyCKI4XQ0utSL8uy4l6I=";
    };
    date = "2023-05-05";
  };
  lualine = {
    pname = "lualine";
    version = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
    src = fetchgit {
      url = "https://github.com/nvim-lualine/lualine.nvim";
      rev = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-v8finXk+sLNaFMA7pSHhEu0WF5mhPYWHEKhl0IKBv8c=";
    };
    date = "2023-08-03";
  };
  moonfly = {
    pname = "moonfly";
    version = "49a0f8aa5aa59af01b2305bb01d96ebd3a78f758";
    src = fetchgit {
      url = "https://github.com/bluz71/vim-moonfly-colors";
      rev = "49a0f8aa5aa59af01b2305bb01d96ebd3a78f758";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2GwbNuuj7B0tvSdJjnP3pV9WTAxKvBUSIlOyKJ0hh1I=";
    };
    date = "2023-08-19";
  };
  neogen = {
    pname = "neogen";
    version = "1dd0319ccf41b2498f45a3c7607f2ee325ffc6a0";
    src = fetchgit {
      url = "https://github.com/danymat/neogen";
      rev = "1dd0319ccf41b2498f45a3c7607f2ee325ffc6a0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7qsYR3xJzkZujT38VtX0A8B4gDjRIXErvptpTy8mhjg=";
    };
    date = "2023-06-09";
  };
  neorg = {
    pname = "neorg";
    version = "f296a22864bbac0d94ad00fa18cc8231dbeaa1e3";
    src = fetchgit {
      url = "https://github.com/nvim-neorg/neorg";
      rev = "f296a22864bbac0d94ad00fa18cc8231dbeaa1e3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-LdIhJfeqJ9RW96rgqnLy3bT/YhzfUx2FP2idmreApPU=";
    };
    date = "2023-08-14";
  };
  neorg-telescope = {
    pname = "neorg-telescope";
    version = "1310d4aaefd8149c9839bbe1d5610e94389e2f0e";
    src = fetchgit {
      url = "https://github.com/nvim-neorg/neorg-telescope";
      rev = "1310d4aaefd8149c9839bbe1d5610e94389e2f0e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-jVfpSWPjSSbbsQns8n7TaAiSJLZ9EPEYVl8mibKH8Mw=";
    };
    date = "2023-08-06";
  };
  noice = {
    pname = "noice";
    version = "894db25ec726d32047799d4d0a982b701bec453b";
    src = fetchgit {
      url = "https://github.com/folke/noice.nvim";
      rev = "894db25ec726d32047799d4d0a982b701bec453b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Zca6meJkfF4fl17Y+6s77GYrqnhkkzIYW73vAhKg7e4=";
    };
    date = "2023-07-25";
  };
  notify = {
    pname = "notify";
    version = "ea9c8ce7a37f2238f934e087c255758659948e0f";
    src = fetchgit {
      url = "https://github.com/rcarriga/nvim-notify";
      rev = "ea9c8ce7a37f2238f934e087c255758659948e0f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Rr2tzuEr06M9ZbvQbC07qcxkyjFJFYdABwRpYelKBFI=";
    };
    date = "2023-06-05";
  };
  nui = {
    pname = "nui";
    version = "9e3916e784660f55f47daa6f26053ad044db5d6a";
    src = fetchgit {
      url = "https://github.com/MunifTanjim/nui.nvim";
      rev = "9e3916e784660f55f47daa6f26053ad044db5d6a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nSUs9zAX7hQ3PuFrH4zQblMfTY6ALDNggmqaQnkbR5E=";
    };
    date = "2023-07-20";
  };
  null-ls = {
    pname = "null-ls";
    version = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7";
    src = fetchgit {
      url = "https://github.com/jose-elias-alvarez/null-ls.nvim";
      rev = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cWA0rzkOp/ekVKaFee7iea1lhnqKtWUIU+fW5M950wI=";
    };
    date = "2023-08-11";
  };
  nvim-colorzier = {
    pname = "nvim-colorzier";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchgit {
      url = "https://github.com/norcalli/nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
    date = "2020-06-11";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "f7922e59aeb9bc3e31a660ea4e7405ffa3fc2c3a";
    src = fetchgit {
      url = "https://github.com/neovim/nvim-lspconfig";
      rev = "f7922e59aeb9bc3e31a660ea4e7405ffa3fc2c3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3eGVtIHobM0YGC2eRaanzty/K80LsNB5QbabZWHoEgE=";
    };
    date = "2023-08-23";
  };
  parinfer = {
    pname = "parinfer";
    version = "5ca09287ab3f4144f78ff7977fabc27466f71044";
    src = fetchgit {
      url = "https://github.com/gpanders/nvim-parinfer";
      rev = "5ca09287ab3f4144f78ff7977fabc27466f71044";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-diwLtmch8LzaX7FIwBNy78n3iY7VnqMC1n0ep8k5kWE=";
    };
    date = "2023-08-09";
  };
  plenary = {
    pname = "plenary";
    version = "0dbe561ae023f02c2fb772b879e905055b939ce3";
    src = fetchgit {
      url = "https://github.com/nvim-lua/plenary.nvim";
      rev = "0dbe561ae023f02c2fb772b879e905055b939ce3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TcjgafIbwNXxoAO5wrf/Wr6sZHJtfpHU9R7RIjBZgkg=";
    };
    date = "2023-08-24";
  };
  smart-splits = {
    pname = "smart-splits";
    version = "7aad6019dee974a01333523a5b8e122b7e7da454";
    src = fetchgit {
      url = "https://github.com/mrjones2014/smart-splits.nvim";
      rev = "7aad6019dee974a01333523a5b8e122b7e7da454";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mLLh8rcq5D6dA9Iwn3ULiHRG/jI4Sjct4J498C+QPO8=";
    };
    date = "2023-06-26";
  };
  startup = {
    pname = "startup";
    version = "5295eabe35eb66d0b355ada0ca06ec8bdb8f9698";
    src = fetchgit {
      url = "https://github.com/startup-nvim/startup.nvim";
      rev = "5295eabe35eb66d0b355ada0ca06ec8bdb8f9698";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WB9NVv2sv8ZAFuM5zcg9akFsqVNl0JBhNIwixwfrf2I=";
    };
    date = "2023-03-13";
  };
  telescope = {
    pname = "telescope";
    version = "2d92125620417fbea82ec30303823e3cd69e90e8";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope.nvim";
      rev = "2d92125620417fbea82ec30303823e3cd69e90e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BU6LFfuloNDhGSFS55sehZAX6mIqpD+R4X+sfu8aZwQ=";
    };
    date = "2023-08-10";
  };
  telescope-file-browser = {
    pname = "telescope-file-browser";
    version = "ad7b637c72549713b9aaed7c4f9c79c62bcbdff0";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope-file-browser.nvim";
      rev = "ad7b637c72549713b9aaed7c4f9c79c62bcbdff0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-iq2KyNU5U/j0zVvWg0q9TAXolHjbxL4d2GyMW/e1+Lo=";
    };
    date = "2023-08-13";
  };
  toggle-term = {
    pname = "toggle-term";
    version = "12cba0a1967b4f3f31903484dec72a6100dcf515";
    src = fetchgit {
      url = "https://github.com/akinsho/toggleterm.nvim";
      rev = "12cba0a1967b4f3f31903484dec72a6100dcf515";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-VFTnDLGy8U3x5ldMUW6okQjQ78qEFPb1n3pcbS2znNY=";
    };
    date = "2023-08-03";
  };
  treesitter = {
    pname = "treesitter";
    version = "31f608e47b838594d32a7bc42028e2cefd0ddaad";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter";
      rev = "31f608e47b838594d32a7bc42028e2cefd0ddaad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Nf5ESttBjqsUe1u//U2NpZm4DT+HSkQS0Yy2oADYzL0=";
    };
    date = "2023-08-24";
  };
  treesitter-context = {
    pname = "treesitter-context";
    version = "ce583c89c8db8d34cd5dff0dc91e13b446fdbe50";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter-context";
      rev = "ce583c89c8db8d34cd5dff0dc91e13b446fdbe50";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-C+4Ho4WQZako6+90yhRWsoPRDfv3HO9b3eSBCeF0nP0=";
    };
    date = "2023-08-23";
  };
  trouble = {
    pname = "trouble";
    version = "40aad004f53ae1d1ba91bcc5c29d59f07c5f01d3";
    src = fetchgit {
      url = "https://github.com/folke/trouble.nvim";
      rev = "40aad004f53ae1d1ba91bcc5c29d59f07c5f01d3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Ee0AM8S/A8DU0hyOnZoKC1hkW0fvk0A+c3WGvPqmKcU=";
    };
    date = "2023-07-29";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "1e8d3cc4d74f40fb384cd1739739543fe117ff61";
    src = fetchgit {
      url = "https://github.com/LnL7/vim-nix";
      rev = "1e8d3cc4d74f40fb384cd1739739543fe117ff61";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x6/WNMWFbR/1uLAeMawlwmp4b1ak+YRWu7abwx+9TRs=";
    };
    date = "2023-07-29";
  };
  vimtex = {
    pname = "vimtex";
    version = "534fd725f2475a9083b032e402c7e73b8a3fc6bb";
    src = fetchgit {
      url = "https://github.com/lervag/vimtex";
      rev = "534fd725f2475a9083b032e402c7e73b8a3fc6bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZL6CYqiHEpx/qatYmap9Hc2qO1Je9llulwFUEOS2LkQ=";
    };
    date = "2023-08-19";
  };
  web-devicons = {
    pname = "web-devicons";
    version = "cfc8824cc1db316a276b36517f093baccb8e799a";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-web-devicons";
      rev = "cfc8824cc1db316a276b36517f093baccb8e799a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6iuZbUi7MA69/wIMijCWj3J1s2RrCWKxQ/l7fWDnOF0=";
    };
    date = "2023-08-17";
  };
  which-key = {
    pname = "which-key";
    version = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
    src = fetchgit {
      url = "https://github.com/folke/which-key.nvim";
      rev = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-B1+EHd2eH/EbD5Kip9PfhdPyyGfIkD6rsx0Z3rXvb5w=";
    };
    date = "2023-07-28";
  };
  yuck-vim = {
    pname = "yuck-vim";
    version = "9b5e0370f70cc30383e1dabd6c215475915fe5c3";
    src = fetchgit {
      url = "https://github.com/elkowar/yuck.vim";
      rev = "9b5e0370f70cc30383e1dabd6c215475915fe5c3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-F7aS8d6jJQQoIGkG2o4KNnDZAIrq0c+otIHvjdoGbtY=";
    };
    date = "2022-10-29";
  };
}
