# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bufdelete-nvim = {
    pname = "bufdelete-nvim";
    version = "07d1f8ba79dec59d42b975a4df1c732b2e4e37b4";
    src = fetchgit {
      url = "https://github.com/famiu/bufdelete.nvim";
      rev = "07d1f8ba79dec59d42b975a4df1c732b2e4e37b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UubYRfRAXZ89WOc3QFMvAMjNjLW6bV4nDgSa1CRZkIM=";
    };
    date = "2023-06-29";
  };
  bufferline-lua = {
    pname = "bufferline-lua";
    version = "99f0932365b34e22549ff58e1bea388465d15e99";
    src = fetchgit {
      url = "https://github.com/akinsho/bufferline.nvim";
      rev = "99f0932365b34e22549ff58e1bea388465d15e99";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-MiQsYeLgADCaUf1x88q/7gO17F992HMlt1pu9dYEmp0=";
    };
    date = "2023-07-24";
  };
  comment = {
    pname = "comment";
    version = "d0cbbfb539898a275dc4398446ab0ae3b94819bf";
    src = fetchgit {
      url = "https://github.com/numToStr/Comment.nvim";
      rev = "d0cbbfb539898a275dc4398446ab0ae3b94819bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6S5P2K5JzNj38rH5wz6O6G2P2w4Pt7CFg7/rdpsvCzc=";
    };
    date = "2023-08-02";
  };
  conjure = {
    pname = "conjure";
    version = "2482871cbe0d1b85d331465cf7f065d5d2a7e2ac";
    src = fetchgit {
      url = "https://github.com/Olical/conjure";
      rev = "2482871cbe0d1b85d331465cf7f065d5d2a7e2ac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-700AhkKvc1X/Q/+YaLuDFlDzNKcd3kuXbMb9NIG7tMo=";
    };
    date = "2023-07-11";
  };
  coq = {
    pname = "coq";
    version = "950df6bf2c818eca310933ab1b319fd8972c1805";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq.artifacts";
      rev = "950df6bf2c818eca310933ab1b319fd8972c1805";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PlwOn5OGr7l27jBtMUAPllM9jLcWWMQZq+nwkB4rSWk=";
    };
    date = "2023-08-01";
  };
  coq_3p = {
    pname = "coq_3p";
    version = "8dfe289b5bde380be5cf7ffb51487099ba312d7a";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq.thirdparty";
      rev = "8dfe289b5bde380be5cf7ffb51487099ba312d7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GkxYT5DwtbIooP/ZTwnEinqSgp1NLgr25L5GLlSB9YY=";
    };
    date = "2023-07-30";
  };
  coq_nvim = {
    pname = "coq_nvim";
    version = "f066e83d886a2525c592b421be20d91307a1c9ec";
    src = fetchgit {
      url = "https://github.com/ms-jpq/coq_nvim";
      rev = "f066e83d886a2525c592b421be20d91307a1c9ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7PyYRp6SsMg7JWAbAJPWaXajO5MQZIV8ewbIw0Q1F4Q=";
    };
    date = "2023-08-03";
  };
  crates = {
    pname = "crates";
    version = "4ce7c51b881e58f1e2f8f437f30e4e583cbac319";
    src = fetchgit {
      url = "https://github.com/saecki/crates.nvim";
      rev = "4ce7c51b881e58f1e2f8f437f30e4e583cbac319";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ah+fTmzkZn+xuL3sG2RxlCtDiFsRv3SY1iJzYKMIaMg=";
    };
    date = "2023-07-02";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "5d73da785a3c05fd63ac31769079db05169a6ec7";
    src = fetchgit {
      url = "https://github.com/lewis6991/gitsigns.nvim";
      rev = "5d73da785a3c05fd63ac31769079db05169a6ec7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kraK0GP5aLGbh1eVZCm41D6BztjFxthSXGnE5CxhrZs=";
    };
    date = "2023-07-27";
  };
  hardtime = {
    pname = "hardtime";
    version = "902a2e75d73bc1f6e5cf75da8c53137c566a6101";
    src = fetchgit {
      url = "https://github.com/m4xshen/hardtime.nvim";
      rev = "902a2e75d73bc1f6e5cf75da8c53137c566a6101";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CI9VEJiu7ljusldxaXwUzb5GXxdOtkOWpMEwv5yU4gM=";
    };
    date = "2023-07-27";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "4541d690816cb99a7fc248f1486aa87f3abce91c";
    src = fetchgit {
      url = "https://github.com/lukas-reineke/indent-blankline.nvim";
      rev = "4541d690816cb99a7fc248f1486aa87f3abce91c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-efMRkxjbr6o7kSKAEn0Kaw8lsDubRmc1N0Kd1BZ3A7k=";
    };
    date = "2023-07-07";
  };
  lazy-lsp = {
    pname = "lazy-lsp";
    version = "c35cb31854f87aece550404103d6ca921b2689aa";
    src = fetchgit {
      url = "https://github.com/dundalek/lazy-lsp.nvim";
      rev = "c35cb31854f87aece550404103d6ca921b2689aa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kjfygsVKZAOU+h1GaPxSo26/UWxaqhSGQl4Ad/55jEY=";
    };
    date = "2023-07-10";
  };
  lspkind = {
    pname = "lspkind";
    version = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
    src = fetchgit {
      url = "https://github.com/onsails/lspkind.nvim";
      rev = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-S+qZm51hw/cRujIfHV/1x1fYyCKI4XQ0utSL8uy4l6I=";
    };
    date = "2023-05-05";
  };
  lualine = {
    pname = "lualine";
    version = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
    src = fetchgit {
      url = "https://github.com/nvim-lualine/lualine.nvim";
      rev = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-v8finXk+sLNaFMA7pSHhEu0WF5mhPYWHEKhl0IKBv8c=";
    };
    date = "2023-08-03";
  };
  neogen = {
    pname = "neogen";
    version = "1dd0319ccf41b2498f45a3c7607f2ee325ffc6a0";
    src = fetchgit {
      url = "https://github.com/danymat/neogen";
      rev = "1dd0319ccf41b2498f45a3c7607f2ee325ffc6a0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7qsYR3xJzkZujT38VtX0A8B4gDjRIXErvptpTy8mhjg=";
    };
    date = "2023-06-09";
  };
  neorg = {
    pname = "neorg";
    version = "1c41592ec975189c79987aa32228778c111eb67f";
    src = fetchgit {
      url = "https://github.com/nvim-neorg/neorg";
      rev = "1c41592ec975189c79987aa32228778c111eb67f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cw3B5fh1jZ2iEQDGD2j+HrkcOQ1oAAJxmXVdyDTqqRc=";
    };
    date = "2023-08-01";
  };
  neorg-telescope = {
    pname = "neorg-telescope";
    version = "d803ae41c40e3dfa2ac11a4956497436b101ce80";
    src = fetchgit {
      url = "https://github.com/nvim-neorg/neorg-telescope";
      rev = "d803ae41c40e3dfa2ac11a4956497436b101ce80";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4wJuzJ09gJMNoxGwQ5GVbdE9zr7liwJI8eGMWodsJe4=";
    };
    date = "2023-08-01";
  };
  nui = {
    pname = "nui";
    version = "9e3916e784660f55f47daa6f26053ad044db5d6a";
    src = fetchgit {
      url = "https://github.com/MunifTanjim/nui.nvim";
      rev = "9e3916e784660f55f47daa6f26053ad044db5d6a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nSUs9zAX7hQ3PuFrH4zQblMfTY6ALDNggmqaQnkbR5E=";
    };
    date = "2023-07-20";
  };
  null-ls = {
    pname = "null-ls";
    version = "db09b6c691def0038c456551e4e2772186449f35";
    src = fetchgit {
      url = "https://github.com/jose-elias-alvarez/null-ls.nvim";
      rev = "db09b6c691def0038c456551e4e2772186449f35";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6KJtj9pbvBm6fOVpnyzO2fEVC+cVrw2XtZHOgq9ieIw=";
    };
    date = "2023-07-06";
  };
  nvim-colorzier = {
    pname = "nvim-colorzier";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchgit {
      url = "https://github.com/norcalli/nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
    date = "2020-06-11";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "a59d74e12340242c0735666fb2e91afdbe6f2496";
    src = fetchgit {
      url = "https://github.com/neovim/nvim-lspconfig";
      rev = "a59d74e12340242c0735666fb2e91afdbe6f2496";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X3LdOeCZoxNH5hHAYQntLJF9HCPs1yKO3qiHqVhE7DY=";
    };
    date = "2023-08-01";
  };
  oxocarbon = {
    pname = "oxocarbon";
    version = "12a7507f1cd5ac6edb890d12268e4444a35956f2";
    src = fetchgit {
      url = "https://github.com/nyoom-engineering/oxocarbon.nvim";
      rev = "12a7507f1cd5ac6edb890d12268e4444a35956f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-OcCplmC62wkVxk5vuutbMD/4usWBAD/Qd96A7s2cylA=";
    };
    date = "2023-06-06";
  };
  parinfer = {
    pname = "parinfer";
    version = "c0d95d9f4c5f921872ba11790b76efbb02cc8af5";
    src = fetchgit {
      url = "https://github.com/gpanders/nvim-parinfer";
      rev = "c0d95d9f4c5f921872ba11790b76efbb02cc8af5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xJmVZyoNgKtOyqSBhkLEQuF3kcwI/sKoyfb3fS+3Zmo=";
    };
    date = "2023-04-08";
  };
  plenary = {
    pname = "plenary";
    version = "267282a9ce242bbb0c5dc31445b6d353bed978bb";
    src = fetchgit {
      url = "https://github.com/nvim-lua/plenary.nvim";
      rev = "267282a9ce242bbb0c5dc31445b6d353bed978bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oRtNcURQzrIRS3D88tWAl3HuFHxVJr8m/zzL7xoa/II=";
    };
    date = "2023-07-17";
  };
  smart-splits = {
    pname = "smart-splits";
    version = "7aad6019dee974a01333523a5b8e122b7e7da454";
    src = fetchgit {
      url = "https://github.com/mrjones2014/smart-splits.nvim";
      rev = "7aad6019dee974a01333523a5b8e122b7e7da454";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mLLh8rcq5D6dA9Iwn3ULiHRG/jI4Sjct4J498C+QPO8=";
    };
    date = "2023-06-26";
  };
  startup = {
    pname = "startup";
    version = "5295eabe35eb66d0b355ada0ca06ec8bdb8f9698";
    src = fetchgit {
      url = "https://github.com/startup-nvim/startup.nvim";
      rev = "5295eabe35eb66d0b355ada0ca06ec8bdb8f9698";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WB9NVv2sv8ZAFuM5zcg9akFsqVNl0JBhNIwixwfrf2I=";
    };
    date = "2023-03-13";
  };
  telescope = {
    pname = "telescope";
    version = "d2e17ba18a6840b7e7079764b282616c3188e0de";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope.nvim";
      rev = "d2e17ba18a6840b7e7079764b282616c3188e0de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-RtnsN0lssWAAXYPnzxqdVuALGfnrsMCrqRs7cQyP6TU=";
    };
    date = "2023-08-01";
  };
  telescope-file-browser = {
    pname = "telescope-file-browser";
    version = "6fe423eea6604c2fcbb906ff5f7e27f748a6ed87";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope-file-browser.nvim";
      rev = "6fe423eea6604c2fcbb906ff5f7e27f748a6ed87";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PVg0ZDqF4ABBJ24oF/9GSJkiJrXqcYX1GP0rgGXgk8E=";
    };
    date = "2023-07-30";
  };
  toggle-term = {
    pname = "toggle-term";
    version = "12cba0a1967b4f3f31903484dec72a6100dcf515";
    src = fetchgit {
      url = "https://github.com/akinsho/toggleterm.nvim";
      rev = "12cba0a1967b4f3f31903484dec72a6100dcf515";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-VFTnDLGy8U3x5ldMUW6okQjQ78qEFPb1n3pcbS2znNY=";
    };
    date = "2023-08-03";
  };
  treesitter = {
    pname = "treesitter";
    version = "131f665f9008d69d130f76f77603886e75c4b146";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter";
      rev = "131f665f9008d69d130f76f77603886e75c4b146";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3bH1sPhI0AMnefwaF9xXZx9HZioX8wdSliTZTpvuKsE=";
    };
    date = "2023-08-03";
  };
  treesitter-context = {
    pname = "treesitter-context";
    version = "3d4ab25056dcaf6dd11ebacf1da8525c8df6550f";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter-context";
      rev = "3d4ab25056dcaf6dd11ebacf1da8525c8df6550f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gOf7ZwExcZePJp9o0z4fXaTsdBKfow/AAwT5X00nvgk=";
    };
    date = "2023-08-03";
  };
  trouble = {
    pname = "trouble";
    version = "40aad004f53ae1d1ba91bcc5c29d59f07c5f01d3";
    src = fetchgit {
      url = "https://github.com/folke/trouble.nvim";
      rev = "40aad004f53ae1d1ba91bcc5c29d59f07c5f01d3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Ee0AM8S/A8DU0hyOnZoKC1hkW0fvk0A+c3WGvPqmKcU=";
    };
    date = "2023-07-29";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "1e8d3cc4d74f40fb384cd1739739543fe117ff61";
    src = fetchgit {
      url = "https://github.com/LnL7/vim-nix";
      rev = "1e8d3cc4d74f40fb384cd1739739543fe117ff61";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x6/WNMWFbR/1uLAeMawlwmp4b1ak+YRWu7abwx+9TRs=";
    };
    date = "2023-07-29";
  };
  vimtex = {
    pname = "vimtex";
    version = "877de3ba5de5f766e5bfa1c3fb0d2ecfcd18f868";
    src = fetchgit {
      url = "https://github.com/lervag/vimtex";
      rev = "877de3ba5de5f766e5bfa1c3fb0d2ecfcd18f868";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WCe4Y6vdpaJvYQltG1xCOZ7t0IJpPVuGutZYghRI3/s=";
    };
    date = "2023-07-25";
  };
  web-devicons = {
    pname = "web-devicons";
    version = "efbfed0567ef4bfac3ce630524a0f6c8451c5534";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-web-devicons";
      rev = "efbfed0567ef4bfac3ce630524a0f6c8451c5534";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FtEJBhqvs+c/Rvy4qXf3iyoMTTKrDBvQw5g63n4KEYo=";
    };
    date = "2023-07-16";
  };
  which-key = {
    pname = "which-key";
    version = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
    src = fetchgit {
      url = "https://github.com/folke/which-key.nvim";
      rev = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-B1+EHd2eH/EbD5Kip9PfhdPyyGfIkD6rsx0Z3rXvb5w=";
    };
    date = "2023-07-28";
  };
  yuck-vim = {
    pname = "yuck-vim";
    version = "9b5e0370f70cc30383e1dabd6c215475915fe5c3";
    src = fetchgit {
      url = "https://github.com/elkowar/yuck.vim";
      rev = "9b5e0370f70cc30383e1dabd6c215475915fe5c3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-F7aS8d6jJQQoIGkG2o4KNnDZAIrq0c+otIHvjdoGbtY=";
    };
    date = "2022-10-29";
  };
}
